### PR TITLE
Loosen regex on parseVersionOutput for build version

### LINKED ISSUE #95: parseVersionOutput matcher doesn't match Java(TM)
This might be a requirement for Adoptium soon as well. We are building binaries where we have changed `PRODUCT_NAME` and `PRODUCT_SUFFIX` (and `LAUNCHER_NAME`) in the openjdk code (`make/autoconf/version-numbers`). As a result, our JSON build artifacts have `version:null` in them because the version parser looks for `OpenJDK Runtime Environment`
https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/f757ffa251aedcd71cecce9e0c89888a2d53b720/pipelines/build/common/openjdk_build_pipeline.groovy#L310
This fails silently on most platforms but errors out on Windows and Mac because those platforms later try and use that info.
Specifically here
https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/f757ffa251aedcd71cecce9e0c89888a2d53b720/pipelines/build/common/openjdk_build_pipeline.groovy#L331
Which throws
```
01:00:09.031  Execution error: java.lang.NullPointerException: Cannot get property 'major' on null object
[Pipeline] echo
01:00:09.034  java.lang.NullPointerException: Cannot get property 'major' on null object
01:00:09.034  	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
01:00:09.034  	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
01:00:09.034  	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
01:00:09.034  	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:355)
01:00:09.034  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
01:00:09.034  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
01:00:09.034  	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
01:00:09.034  	at Build.sign(Script2.groovy:355)
```

I am requesting either we make the regex more generic, add a second case here or make it configurable.

### PR DESCRIPTION
**Pull request by AdamBrousseau**
For users who want to change the OpenJDK PRODUCT_NAME
and PRODUCT_SUFFIX this will allow the regex to still
match those versions

Fixes #95

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Testing on my side underway.

**Comment by AdamBrousseau** [comment]
Works for both my OpenJDK and Java(TM) use cases. Marking for review.

**Comment by gdams** [comment]
run tests

**Comment by AdamBrousseau** [comment]
Only failure I found in the PR tester looks unrelated
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk/job/jdk-mac-x64-hotspot/514/console
```
00:05:47.812  checking for metal... [not found]
00:05:47.812  checking if metal can be run using xcrun... no
00:05:47.812  configure: error: XCode tool 'metal' neither found in path nor with xcrun
00:05:47.812  configure exiting with result code 1
00:05:47.812  Error: No configurations found for /Users/jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk/jdk-mac-x64-hotspot/workspace/build/src.
00:05:47.812  Please run 'bash configure' to create a configuration.
00:05:47.812  
00:05:47.812  /Users/jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk/jdk-mac-x64-hotspot/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
00:05:47.812  OpenJDK make failed, archiving make failed logs
```

**Review by M-Davies — APPROVED** [review]

File: pipelines/build/common/openjdk_build_pipeline.groovy [hunk 1]
```diff
@@ -307,7 +307,7 @@ class Build {
     */
     VersionInfo parseVersionOutput(String consoleOut) {
         context.println(consoleOut)
-        Matcher matcher = (consoleOut =~ /(?ms)^.*OpenJDK Runtime Environment[^\n]*\(build (?<version>[^)]*)\).*$/)
+        Matcher matcher = (consoleOut =~ /(?ms)^.*Runtime Environment[^\n]*\(build (?<version>[^)]*)\).*$/)
```
Comment (karianna) [inline pipelines/build/common/openjdk_build_pipeline.groovy:310]: Can we expand the comment at the top to include the example you're widening this to?

**Review by karianna — CHANGES_REQUESTED** [review]

File: pipelines/build/common/openjdk_build_pipeline.groovy (hunk 1 above)
Comment (AdamBrousseau) [reply pipelines/build/common/openjdk_build_pipeline.groovy:311]: Updated.

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
run tests

**Comment by karianna** [comment]
```
RepoHandlerTest > userDefaultsSetterAndGetterReturns() FAILED
    groovy.lang.MissingPropertyException: No such property: adoptJson for class: RepoHandlerTest
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at RepoHandlerTest.userDefaultsSetterAndGetterReturns(RepoHandlerTest.groovy:125)

RepoHandlerTest > adoptDefaultsGetterReturns() FAILED
    groovy.lang.MissingMethodException: No signature of method: static org.junit.jupiter.api.Assertions.assertEquals() is applicable for argument types: (Boolean) values: [true]
    Possible solutions: assertEquals(byte, byte), assertEquals(byte, java.lang.Byte), assertEquals(char, char), assertEquals(char, java.lang.Character), assertEquals(double, double), assertEquals(double, java.lang.Double)
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1568)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1554)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at RepoHandlerTest.adoptDefaultsGetterReturns(RepoHandlerTest.groovy:67)
```

**Comment by M-Davies** [comment]
> ```
> RepoHandlerTest > userDefaultsSetterAndGetterReturns() FAILED
>     groovy.lang.MissingPropertyException: No such property: adoptJson for class: RepoHandlerTest
>         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
>         at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
>         at RepoHandlerTest.userDefaultsSetterAndGetterReturns(RepoHandlerTest.groovy:125)
> 
> RepoHandlerTest > adoptDefaultsGetterReturns() FAILED
>     groovy.lang.MissingMethodException: No signature of method: static org.junit.jupiter.api.Assertions.assertEquals() is applicable for argument types: (Boolean) values: [true]
>     Possible solutions: assertEquals(byte, byte), assertEquals(byte, java.lang.Byte), assertEquals(char, char), assertEquals(char, java.lang.Character), assertEquals(double, double), assertEquals(double, java.lang.Double)
>         at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1568)
>         at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1554)
>         at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
>         at RepoHandlerTest.adoptDefaultsGetterReturns(RepoHandlerTest.groovy:67)
> ```

Unrelated. To be fixed by https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/110
